-- sis_chatbot_db schema.
-- Column lists are taken verbatim from backend/sample_table/*.csv.
-- Generated by backend/sample_db/schema_builder.py -- do not hand-edit.

DROP TABLE IF EXISTS urban_application_log CASCADE;
CREATE TABLE urban_application_log (
    row_id BIGSERIAL PRIMARY KEY,
    serial_number INTEGER,
    user_id VARCHAR(60),
    department_code VARCHAR(60),
    service_code VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    village_code VARCHAR(60),
    urban_unit_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    application_date DATE,
    application_status VARCHAR(200),
    last_updated_datetime TIMESTAMP,
    application_id VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    patta_number VARCHAR(60),
    role_id VARCHAR(60),
    source_code VARCHAR(60),
    csc_service_charge NUMERIC(14,2),
    government_service_charge NUMERIC(14,2),
    can_number VARCHAR(60),
    dispatch_date DATE,
    received_date DATE,
    ip_address VARCHAR(60),
    generated_datetime TIMESTAMP,
    source_name VARCHAR(60),
    renewal_number VARCHAR(60),
    workflow_state VARCHAR(60),
    igrs_form6_number VARCHAR(60),
    return_status VARCHAR(60),
    current_subdivision_number VARCHAR(60),
    parent_application_id VARCHAR(60),
    auto_mutated_flag VARCHAR(60),
    is_auto_mutated VARCHAR(60),
    igrs_auto_mutation_flag VARCHAR(60),
    camp_flag VARCHAR(60),
    camp_correction_id VARCHAR(60),
    camp_code VARCHAR(60)
);
CREATE INDEX idx_urban_application_log_service_code ON urban_application_log (service_code);
CREATE INDEX idx_urban_application_log_district_code ON urban_application_log (district_code);
CREATE INDEX idx_urban_application_log_application_status ON urban_application_log (application_status);
CREATE INDEX idx_urban_application_log_application_id ON urban_application_log (application_id);
CREATE INDEX idx_urban_application_log_survey_number ON urban_application_log (survey_number);
CREATE INDEX idx_urban_application_log_patta_number ON urban_application_log (patta_number);

DROP TABLE IF EXISTS application_workflow_action CASCADE;
CREATE TABLE application_workflow_action (
    row_id BIGSERIAL PRIMARY KEY,
    serial_number INTEGER,
    application_id VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    village_code VARCHAR(60),
    action_from_role_id VARCHAR(60),
    action_to_role_id VARCHAR(60),
    action_date DATE,
    remarks TEXT,
    action_status VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    updated_by_user VARCHAR(60),
    workflow_state VARCHAR(60),
    recommendation_status VARCHAR(60),
    field_visit_date DATE,
    received_flag VARCHAR(60),
    annual_income NUMERIC(14,2),
    review_flag VARCHAR(60),
    ip_address VARCHAR(60),
    auto_recommendation_flag VARCHAR(60),
    auto_recommendation_remarks TEXT
);
CREATE INDEX idx_application_workflow_action_application_id ON application_workflow_action (application_id);
CREATE INDEX idx_application_workflow_action_district_code ON application_workflow_action (district_code);

DROP TABLE IF EXISTS urban_temp_subdivision_parcel CASCADE;
CREATE TABLE urban_temp_subdivision_parcel (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    survey_number VARCHAR(60),
    temporary_subdivision_number VARCHAR(60),
    new_subdivision_number VARCHAR(60),
    existing_patta_number VARCHAR(60),
    area_hectare NUMERIC(14,2),
    area_ares NUMERIC(14,2),
    area_square_meter NUMERIC(14,2),
    new_patta_waste VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    submitted_datetime TIMESTAMP,
    land_type VARCHAR(60),
    government_private_flag VARCHAR(60),
    tax_rate NUMERIC(14,2),
    tax_per_hectare NUMERIC(14,2),
    primary_soil_type VARCHAR(60),
    secondary_soil_type VARCHAR(60),
    adopted_area_hectare NUMERIC(14,2),
    adopted_area_ares NUMERIC(14,2),
    status VARCHAR(60),
    adopted_area_square_meter NUMERIC(14,2),
    surveyor_adopted_area_hectare NUMERIC(14,2),
    surveyor_adopted_area_ares NUMERIC(14,2),
    surveyor_adopted_area_square_meter NUMERIC(14,2),
    district_adopted_area_hectare NUMERIC(14,2),
    district_adopted_area_ares NUMERIC(14,2),
    district_adopted_area_square_meter NUMERIC(14,2),
    new_patta_number VARCHAR(60),
    group_survey_number VARCHAR(60),
    group_subdivision_number VARCHAR(60),
    group_temporary_subdivision_number VARCHAR(60),
    group_patta_number VARCHAR(60),
    plot_type VARCHAR(60),
    plot_number VARCHAR(60),
    land_use VARCHAR(200),
    land_use_description VARCHAR(200)
);
CREATE INDEX idx_urban_temp_subdivision_parcel_application_id ON urban_temp_subdivision_parcel (application_id);
CREATE INDEX idx_urban_temp_subdivision_parcel_district_code ON urban_temp_subdivision_parcel (district_code);
CREATE INDEX idx_urban_temp_subdivision_parcel_survey_number ON urban_temp_subdivision_parcel (survey_number);

DROP TABLE IF EXISTS urban_temp_subdivision_owner CASCADE;
CREATE TABLE urban_temp_subdivision_owner (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    owner_name_tamil VARCHAR(200),
    relationship VARCHAR(200),
    relative_name_tamil VARCHAR(200),
    extent_value_1 NUMERIC(14,2),
    extent_value_2 NUMERIC(14,2),
    extent_value_3 NUMERIC(14,2),
    patta_number VARCHAR(60),
    relation_code VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    survey_number VARCHAR(60),
    temporary_subdivision_number VARCHAR(60),
    new_subdivision_number VARCHAR(60),
    existing_patta_number VARCHAR(60),
    owner_no INTEGER,
    status VARCHAR(60),
    owner_name_english VARCHAR(200),
    relative_name_english VARCHAR(200),
    ownership_share VARCHAR(60),
    aadhaar_number VARCHAR(60),
    gender VARCHAR(60)
);
CREATE INDEX idx_urban_temp_subdivision_owner_application_id ON urban_temp_subdivision_owner (application_id);
CREATE INDEX idx_urban_temp_subdivision_owner_patta_number ON urban_temp_subdivision_owner (patta_number);
CREATE INDEX idx_urban_temp_subdivision_owner_district_code ON urban_temp_subdivision_owner (district_code);
CREATE INDEX idx_urban_temp_subdivision_owner_survey_number ON urban_temp_subdivision_owner (survey_number);

DROP TABLE IF EXISTS nisd_transfer_application_info CASCADE;
CREATE TABLE nisd_transfer_application_info (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    can_number VARCHAR(60),
    applicant_name VARCHAR(200),
    current_address TEXT,
    mobile_number VARCHAR(60),
    application_status VARCHAR(200),
    remarks TEXT,
    last_updated_datetime TIMESTAMP,
    permanent_address TEXT,
    mother_name VARCHAR(60),
    father_name VARCHAR(60),
    date_of_birth DATE,
    gender VARCHAR(60),
    occupation VARCHAR(200),
    enclosure_details TEXT,
    barcode_flag VARCHAR(60),
    first_page_document TEXT,
    reverse_page_document TEXT,
    last_page_document TEXT,
    enclosure_certificate VARCHAR(60),
    proposed_field_visit_date DATE,
    proposed_remarks VARCHAR(200),
    missing_documents TEXT,
    physical_verification_status VARCHAR(200),
    document_sent_date DATE,
    document_received_date DATE,
    challan_number VARCHAR(60),
    challan_date DATE,
    treasury_name VARCHAR(200),
    bank_name VARCHAR(200),
    bank_branch VARCHAR(200),
    payment_mode VARCHAR(60),
    payment_amount NUMERIC(14,2),
    igrs_form6_number VARCHAR(60),
    return_status VARCHAR(60),
    owner_correction_reason VARCHAR(200),
    merged_application_id VARCHAR(60),
    auto_mutated_flag VARCHAR(60)
);
CREATE INDEX idx_nisd_transfer_application_info_application_id ON nisd_transfer_application_info (application_id);
CREATE INDEX idx_nisd_transfer_application_info_district_code ON nisd_transfer_application_info (district_code);
CREATE INDEX idx_nisd_transfer_application_info_application_status ON nisd_transfer_application_info (application_status);

DROP TABLE IF EXISTS nisd_transfer_igrs_owner CASCADE;
CREATE TABLE nisd_transfer_igrs_owner (
    row_id BIGSERIAL PRIMARY KEY,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    door_number VARCHAR(60),
    patta_number VARCHAR(60),
    occupation_code VARCHAR(60),
    owner_no INTEGER,
    owner_name_tamil VARCHAR(200),
    owner_name_english VARCHAR(200),
    relation_no INTEGER,
    relative_name_tamil VARCHAR(200),
    relative_name_english VARCHAR(200),
    relation_code VARCHAR(60),
    ownership_share VARCHAR(60),
    address TEXT,
    citizen_identification_number VARCHAR(60),
    form6_number VARCHAR(60),
    assignment_number VARCHAR(60),
    ration_card_number VARCHAR(60),
    voter_id_number VARCHAR(60),
    pin_code VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    user_number VARCHAR(60),
    aadhaar_number VARCHAR(60),
    gender VARCHAR(60),
    igrs_form6_number VARCHAR(60),
    mobile_number VARCHAR(60),
    application_id VARCHAR(60),
    owner_image TEXT
);
CREATE INDEX idx_nisd_transfer_igrs_owner_district_code ON nisd_transfer_igrs_owner (district_code);
CREATE INDEX idx_nisd_transfer_igrs_owner_patta_number ON nisd_transfer_igrs_owner (patta_number);
CREATE INDEX idx_nisd_transfer_igrs_owner_application_id ON nisd_transfer_igrs_owner (application_id);

DROP TABLE IF EXISTS nisd_transfer_new_owner CASCADE;
CREATE TABLE nisd_transfer_new_owner (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    owner_name_tamil VARCHAR(200),
    owner_name_english VARCHAR(200),
    relationship VARCHAR(200),
    relative_name_tamil VARCHAR(200),
    extent VARCHAR(60),
    patta_number VARCHAR(60),
    relation_code VARCHAR(60),
    owner_no INTEGER,
    owner_status VARCHAR(60),
    uds_details TEXT,
    owner_photo TEXT,
    relative_name_english VARCHAR(200),
    ownership_share VARCHAR(60),
    aadhaar_number VARCHAR(60),
    gender VARCHAR(60),
    relation_no INTEGER,
    block_code VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    owner_image TEXT,
    mobile_number VARCHAR(60)
);
CREATE INDEX idx_nisd_transfer_new_owner_application_id ON nisd_transfer_new_owner (application_id);
CREATE INDEX idx_nisd_transfer_new_owner_patta_number ON nisd_transfer_new_owner (patta_number);
CREATE INDEX idx_nisd_transfer_new_owner_survey_number ON nisd_transfer_new_owner (survey_number);
CREATE INDEX idx_nisd_transfer_new_owner_district_code ON nisd_transfer_new_owner (district_code);

DROP TABLE IF EXISTS nisd_transfer_old_owner CASCADE;
CREATE TABLE nisd_transfer_old_owner (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    owner_name_tamil VARCHAR(200),
    owner_name_english VARCHAR(200),
    relationship VARCHAR(200),
    relative_name_tamil VARCHAR(200),
    extent VARCHAR(60),
    patta_number VARCHAR(60),
    relation_code VARCHAR(60),
    owner_no INTEGER,
    owner_status VARCHAR(60),
    uds_details TEXT,
    owner_photo TEXT,
    relative_name_english VARCHAR(200),
    ownership_share VARCHAR(60),
    aadhaar_number VARCHAR(60),
    gender VARCHAR(60),
    relation_no INTEGER,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60)
);
CREATE INDEX idx_nisd_transfer_old_owner_application_id ON nisd_transfer_old_owner (application_id);
CREATE INDEX idx_nisd_transfer_old_owner_patta_number ON nisd_transfer_old_owner (patta_number);
CREATE INDEX idx_nisd_transfer_old_owner_district_code ON nisd_transfer_old_owner (district_code);

DROP TABLE IF EXISTS nisd_transfer_return_owner CASCADE;
CREATE TABLE nisd_transfer_return_owner (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    owner_name_tamil VARCHAR(200),
    owner_name_english VARCHAR(200),
    relationship VARCHAR(200),
    relative_name_tamil VARCHAR(200),
    extent VARCHAR(60),
    patta_number VARCHAR(60),
    relation_code VARCHAR(60),
    owner_no INTEGER,
    owner_status VARCHAR(60),
    uds_details TEXT,
    owner_photo TEXT,
    relative_name_english VARCHAR(200),
    ownership_share VARCHAR(60),
    aadhaar_number VARCHAR(60),
    gender VARCHAR(60),
    relation_no INTEGER,
    return_status VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    owner_image TEXT,
    mobile_number VARCHAR(60)
);
CREATE INDEX idx_nisd_transfer_return_owner_application_id ON nisd_transfer_return_owner (application_id);
CREATE INDEX idx_nisd_transfer_return_owner_patta_number ON nisd_transfer_return_owner (patta_number);
CREATE INDEX idx_nisd_transfer_return_owner_district_code ON nisd_transfer_return_owner (district_code);

DROP TABLE IF EXISTS nisd_transfer_urban_detail CASCADE;
CREATE TABLE nisd_transfer_urban_detail (
    row_id BIGSERIAL PRIMARY KEY,
    slno INTEGER,
    sno INTEGER,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    application_id VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    old_patta_number VARCHAR(60),
    land_type_code VARCHAR(60),
    extent_value_1 NUMERIC(14,2),
    extent_value_2 NUMERIC(14,2),
    extent_value_3 NUMERIC(14,2),
    registration_document_number VARCHAR(60),
    transfer_reason VARCHAR(200),
    registration_place VARCHAR(200),
    registration_date DATE,
    generated_patta_number VARCHAR(60),
    transaction_status VARCHAR(60),
    order_number VARCHAR(60),
    order_date DATE,
    order_remarks TEXT,
    last_updated_datetime TIMESTAMP,
    submitted_datetime TIMESTAMP,
    extent_in_ares NUMERIC(14,2),
    tax_rate NUMERIC(14,2),
    succession_certificate_number VARCHAR(60),
    succession_certificate_date DATE,
    succession_certificate_issued_by VARCHAR(200),
    legal_heir_certificate_issue_place VARCHAR(200),
    court_order_number VARCHAR(60),
    court_order_date DATE,
    court_name VARCHAR(200),
    street_code VARCHAR(60),
    purchased_area NUMERIC(14,2),
    purchased_area_unit VARCHAR(60),
    transaction_code VARCHAR(60),
    old_street_code VARCHAR(60),
    sis_recommendation VARCHAR(60),
    sis_remarks TEXT,
    sis_recommendation_reason VARCHAR(200),
    new_door_number VARCHAR(60),
    new_total_tax NUMERIC(14,2),
    old_door_number VARCHAR(60),
    old_total_tax NUMERIC(14,2),
    group_survey_number VARCHAR(60),
    group_subdivision_number VARCHAR(60),
    group_patta_number VARCHAR(60),
    owner_correction_reason VARCHAR(200),
    transfer_type VARCHAR(60),
    direct_transfer_flag VARCHAR(60),
    land_category_code VARCHAR(60)
);
CREATE INDEX idx_nisd_transfer_urban_detail_district_code ON nisd_transfer_urban_detail (district_code);
CREATE INDEX idx_nisd_transfer_urban_detail_application_id ON nisd_transfer_urban_detail (application_id);
CREATE INDEX idx_nisd_transfer_urban_detail_survey_number ON nisd_transfer_urban_detail (survey_number);

DROP TABLE IF EXISTS isd_transfer_application_info CASCADE;
CREATE TABLE isd_transfer_application_info (
    row_id BIGSERIAL PRIMARY KEY,
    application_id VARCHAR(60),
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    can_number VARCHAR(60),
    applicant_name VARCHAR(200),
    current_address TEXT,
    mobile_number VARCHAR(60),
    application_status VARCHAR(200),
    remarks TEXT,
    last_updated_datetime TIMESTAMP,
    application_status_code VARCHAR(60),
    rejection_reason_code VARCHAR(200),
    enclosure_details TEXT,
    challan_number VARCHAR(60),
    challan_date DATE,
    treasury_name VARCHAR(200),
    bank_name VARCHAR(200),
    bank_branch VARCHAR(200),
    payment_mode VARCHAR(60),
    first_page_document TEXT,
    reverse_page_document TEXT,
    last_page_document TEXT,
    sro_code VARCHAR(60),
    enclosure_certificate VARCHAR(60),
    proposed_field_visit_date DATE,
    proposed_remarks VARCHAR(200),
    missing_documents TEXT,
    payment_amount NUMERIC(14,2),
    csc_name VARCHAR(200),
    igrs_form6_number VARCHAR(60),
    return_status VARCHAR(60),
    relative_mobile_number VARCHAR(60),
    permanent_address TEXT,
    mother_name VARCHAR(60),
    father_name VARCHAR(60),
    gender VARCHAR(60),
    date_of_birth DATE,
    merged_application_id VARCHAR(60)
);
CREATE INDEX idx_isd_transfer_application_info_application_id ON isd_transfer_application_info (application_id);
CREATE INDEX idx_isd_transfer_application_info_district_code ON isd_transfer_application_info (district_code);
CREATE INDEX idx_isd_transfer_application_info_application_status ON isd_transfer_application_info (application_status);

DROP TABLE IF EXISTS isd_transfer_urban_detail CASCADE;
CREATE TABLE isd_transfer_urban_detail (
    row_id BIGSERIAL PRIMARY KEY,
    slno INTEGER,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    application_id VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    old_patta_number VARCHAR(60),
    land_type_code VARCHAR(60),
    extent_value_1 NUMERIC(14,2),
    extent_value_2 NUMERIC(14,2),
    extent_value_3 NUMERIC(14,2),
    registration_document_number VARCHAR(60),
    transfer_reason VARCHAR(200),
    registration_date DATE,
    registration_place VARCHAR(200),
    submission_date DATE,
    government_private_flag VARCHAR(60),
    transaction_status VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    submitted_datetime TIMESTAMP,
    form8a_number VARCHAR(60),
    receipt_date DATE,
    tahsildar_receipt_date DATE,
    purchased_area NUMERIC(14,2),
    surveyor_received_date DATE,
    surveyor_completed_date DATE,
    court_order_number VARCHAR(60),
    court_order_date DATE,
    court_name VARCHAR(200),
    purchased_area_unit VARCHAR(60),
    sketch_sent_date DATE,
    sketch_received_date DATE,
    incorporation_date DATE,
    handover_received_date DATE,
    commissioner_change_date DATE,
    street_code VARCHAR(60),
    old_street_code VARCHAR(60),
    sis_recommendation VARCHAR(60),
    sis_remarks TEXT,
    sis_recommendation_reason VARCHAR(200),
    surveyor_recommendation VARCHAR(60),
    surveyor_remarks TEXT,
    surveyor_recommendation_reason VARCHAR(200),
    district_recommendation VARCHAR(60),
    district_remarks TEXT,
    district_recommendation_reason VARCHAR(200),
    tahsildar_recommendation VARCHAR(60),
    tahsildar_remarks TEXT,
    tahsildar_recommendation_reason VARCHAR(200),
    land_category_code VARCHAR(60),
    old_door_number VARCHAR(60),
    new_door_number VARCHAR(60),
    payment_amount NUMERIC(14,2),
    generated_patta_number VARCHAR(60),
    total_subdivisions INTEGER
);
CREATE INDEX idx_isd_transfer_urban_detail_district_code ON isd_transfer_urban_detail (district_code);
CREATE INDEX idx_isd_transfer_urban_detail_application_id ON isd_transfer_urban_detail (application_id);
CREATE INDEX idx_isd_transfer_urban_detail_survey_number ON isd_transfer_urban_detail (survey_number);

DROP TABLE IF EXISTS urban_parcel_register CASCADE;
CREATE TABLE urban_parcel_register (
    row_id BIGSERIAL PRIMARY KEY,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    street_code VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    old_subdivision_number VARCHAR(60),
    old_survey_number VARCHAR(60),
    double_crop_flag VARCHAR(60),
    partition_indicator VARCHAR(60),
    door_number VARCHAR(60),
    government_priority_flag VARCHAR(60),
    land_type_code VARCHAR(60),
    irrigation_source_code VARCHAR(60),
    tax_rate_code VARCHAR(60),
    primary_soil_type VARCHAR(60),
    secondary_soil_type VARCHAR(60),
    soil_class_code VARCHAR(60),
    tax_per_hectare NUMERIC(14,2),
    extent_unit VARCHAR(60),
    extent_value_1 NUMERIC(14,2),
    extent_value_2 NUMERIC(14,2),
    extent_value_3 NUMERIC(14,2),
    total_tax NUMERIC(14,2),
    patta_number VARCHAR(60),
    coss_block_code VARCHAR(60),
    land_use_code VARCHAR(60),
    remarks TEXT,
    remarks1 TEXT,
    new_patta_number VARCHAR(60),
    old_patta_number VARCHAR(60),
    form6_number VARCHAR(60),
    form7_number VARCHAR(60),
    form8_number VARCHAR(60),
    relinquishment_number VARCHAR(60),
    assignment_number VARCHAR(60),
    alienation_number VARCHAR(60),
    acquisition_number VARCHAR(60),
    assessed_flag VARCHAR(60),
    cultivable_flag VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    user_number VARCHAR(60),
    descriptive_remark_code VARCHAR(60),
    descriptive_land_use TEXT,
    municipal_tax NUMERIC(14,2),
    new_door_number VARCHAR(60)
);
CREATE INDEX idx_urban_parcel_register_district_code ON urban_parcel_register (district_code);
CREATE INDEX idx_urban_parcel_register_survey_number ON urban_parcel_register (survey_number);
CREATE INDEX idx_urban_parcel_register_patta_number ON urban_parcel_register (patta_number);

DROP TABLE IF EXISTS urban_parcel_signature CASCADE;
CREATE TABLE urban_parcel_signature (
    row_id BIGSERIAL PRIMARY KEY,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    survey_number VARCHAR(60),
    subdivision_number VARCHAR(60),
    form6_number VARCHAR(60),
    form8_number VARCHAR(60),
    patta_number VARCHAR(60),
    document_hash TEXT,
    digital_signature_content TEXT,
    signed_datetime TIMESTAMP,
    username VARCHAR(60),
    role_id VARCHAR(60),
    dateofverify TIMESTAMP,
    username_verify VARCHAR(60),
    nic_dsign_flag VARCHAR(60)
);
CREATE INDEX idx_urban_parcel_signature_district_code ON urban_parcel_signature (district_code);
CREATE INDEX idx_urban_parcel_signature_survey_number ON urban_parcel_signature (survey_number);
CREATE INDEX idx_urban_parcel_signature_patta_number ON urban_parcel_signature (patta_number);

DROP TABLE IF EXISTS urban_natham_chitta_owner CASCADE;
CREATE TABLE urban_natham_chitta_owner (
    row_id BIGSERIAL PRIMARY KEY,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    door_number VARCHAR(60),
    patta_number VARCHAR(60),
    occupation_code VARCHAR(60),
    own_num INTEGER,
    owner_name_tamil VARCHAR(200),
    owner_name_english VARCHAR(200),
    rel_num INTEGER,
    relative_name_tamil VARCHAR(200),
    relative_name_english VARCHAR(200),
    relationship_code VARCHAR(60),
    ownership_share VARCHAR(60),
    address TEXT,
    cin_no VARCHAR(60),
    form6_number VARCHAR(60),
    assignment_number VARCHAR(60),
    ration_card_number VARCHAR(60),
    epic_no VARCHAR(60),
    pin_code VARCHAR(60),
    last_updated_datetime TIMESTAMP,
    user_no VARCHAR(60),
    aadhaar_number VARCHAR(60),
    sex VARCHAR(60)
);
CREATE INDEX idx_urban_natham_chitta_owner_district_code ON urban_natham_chitta_owner (district_code);
CREATE INDEX idx_urban_natham_chitta_owner_patta_number ON urban_natham_chitta_owner (patta_number);

DROP TABLE IF EXISTS urban_natham_chitta_signature CASCADE;
CREATE TABLE urban_natham_chitta_signature (
    row_id BIGSERIAL PRIMARY KEY,
    district_code VARCHAR(60),
    taluk_code VARCHAR(60),
    town_code VARCHAR(60),
    ward_code VARCHAR(60),
    block_code VARCHAR(60),
    patta_number VARCHAR(60),
    form6_number VARCHAR(60),
    form8_number VARCHAR(60),
    document_hash TEXT,
    signature_content TEXT,
    signed_datetime TIMESTAMP,
    signed_by_username VARCHAR(60),
    verified_datetime TIMESTAMP,
    username_verify VARCHAR(60),
    nic_digital_signature TEXT
);
CREATE INDEX idx_urban_natham_chitta_signature_district_code ON urban_natham_chitta_signature (district_code);
CREATE INDEX idx_urban_natham_chitta_signature_patta_number ON urban_natham_chitta_signature (patta_number);
