# ==============================================================================
# Removes glossary training examples whose "ground truth" answer was actually
# generated by a misrouted intent (the live chatbot had no real glossary
# handler for that term, so the single-turn generator captured whatever wrong
# intent it fell through to -- e.g. "What is Deputy Inspector Surveyor?"
# routed to `field_visits` and got a Field Visits Summary table as its
# "answer"). Training on that teaches the model a false fact.
#
# Strips any example tagged source=glossary whose recorded intent isn't one
# of the intents that actually answer a definition question.
# ==============================================================================

import json
import sys
from pathlib import Path

GOOD_GLOSSARY_INTENTS = {"service_code_lookup", "service_code_guide", "igrs_can_rule"}


def clean(path: Path) -> tuple[int, int]:
    kept = []
    dropped = 0
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            meta = d.get("meta", {}) or {}
            if meta.get("source") in ("glossary", "glossary_reinforced") and \
               meta.get("intent") not in GOOD_GLOSSARY_INTENTS:
                dropped += 1
                continue
            kept.append(d)
    path.write_text("".join(json.dumps(d, ensure_ascii=False) + "\n" for d in kept),
                     encoding="utf-8")
    return len(kept), dropped


if __name__ == "__main__":
    for name in sys.argv[1:]:
        p = Path(name)
        kept, dropped = clean(p)
        print(f"{p}: kept {kept}, dropped {dropped} misrouted-glossary examples")
